// Code generated by informer-gen. DO NOT EDIT.

package v1alpha2

import (
	time "time"

	metricsv1alpha2 "github.com/Azure/azure-k8s-metrics-adapter/pkg/apis/metrics/v1alpha2"
	versioned "github.com/Azure/azure-k8s-metrics-adapter/pkg/client/clientset/versioned"
	internalinterfaces "github.com/Azure/azure-k8s-metrics-adapter/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha2 "github.com/Azure/azure-k8s-metrics-adapter/pkg/client/listers/metrics/v1alpha2"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ExternalMetricInformer provides access to a shared informer and lister for
// ExternalMetrics.
type ExternalMetricInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha2.ExternalMetricLister
}

type externalMetricInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewExternalMetricInformer constructs a new informer for ExternalMetric type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewExternalMetricInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredExternalMetricInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredExternalMetricInformer constructs a new informer for ExternalMetric type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredExternalMetricInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AzureV1alpha2().ExternalMetrics(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AzureV1alpha2().ExternalMetrics(namespace).Watch(options)
			},
		},
		&metricsv1alpha2.ExternalMetric{},
		resyncPeriod,
		indexers,
	)
}

func (f *externalMetricInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredExternalMetricInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *externalMetricInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&metricsv1alpha2.ExternalMetric{}, f.defaultInformer)
}

func (f *externalMetricInformer) Lister() v1alpha2.ExternalMetricLister {
	return v1alpha2.NewExternalMetricLister(f.Informer().GetIndexer())
}
