apiVersion: apps/v1
kind: Deployment
metadata:
  name: rps-sample
spec:
  selector:
    matchLabels:
      app: rps-sample
  template:
    metadata:
      labels:
        app: rps-sample
    spec:
      containers:
      - name: rps-sample
        image: jsturtevant/metric-rps-example
        env:
          - name: INSTRUMENTATION_KEY
            valueFrom:
              secretKeyRef:
                name: appinsightskey
                key: instrumentation-key
---
kind: Service
apiVersion: v1
metadata:
  name: rps-sample
spec:
  selector:
    app: rps-sample
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer
  