/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/Azure/azure-k8s-metrics-adapter/pkg/apis/metrics/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeCustomMetrics implements CustomMetricInterface
type FakeCustomMetrics struct {
	Fake *FakeAzureV1alpha1
	ns   string
}

var custommetricsResource = schema.GroupVersionResource{Group: "azure.com", Version: "v1alpha1", Resource: "custommetrics"}

var custommetricsKind = schema.GroupVersionKind{Group: "azure.com", Version: "v1alpha1", Kind: "CustomMetric"}

// Get takes name of the customMetric, and returns the corresponding customMetric object, and an error if there is any.
func (c *FakeCustomMetrics) Get(name string, options v1.GetOptions) (result *v1alpha1.CustomMetric, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(custommetricsResource, c.ns, name), &v1alpha1.CustomMetric{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CustomMetric), err
}

// List takes label and field selectors, and returns the list of CustomMetrics that match those selectors.
func (c *FakeCustomMetrics) List(opts v1.ListOptions) (result *v1alpha1.CustomMetricList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(custommetricsResource, custommetricsKind, c.ns, opts), &v1alpha1.CustomMetricList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.CustomMetricList{ListMeta: obj.(*v1alpha1.CustomMetricList).ListMeta}
	for _, item := range obj.(*v1alpha1.CustomMetricList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested customMetrics.
func (c *FakeCustomMetrics) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(custommetricsResource, c.ns, opts))

}

// Create takes the representation of a customMetric and creates it.  Returns the server's representation of the customMetric, and an error, if there is any.
func (c *FakeCustomMetrics) Create(customMetric *v1alpha1.CustomMetric) (result *v1alpha1.CustomMetric, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(custommetricsResource, c.ns, customMetric), &v1alpha1.CustomMetric{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CustomMetric), err
}

// Update takes the representation of a customMetric and updates it. Returns the server's representation of the customMetric, and an error, if there is any.
func (c *FakeCustomMetrics) Update(customMetric *v1alpha1.CustomMetric) (result *v1alpha1.CustomMetric, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(custommetricsResource, c.ns, customMetric), &v1alpha1.CustomMetric{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CustomMetric), err
}

// Delete takes name of the customMetric and deletes it. Returns an error if one occurs.
func (c *FakeCustomMetrics) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(custommetricsResource, c.ns, name), &v1alpha1.CustomMetric{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCustomMetrics) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(custommetricsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.CustomMetricList{})
	return err
}

// Patch applies the patch and returns the patched customMetric.
func (c *FakeCustomMetrics) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.CustomMetric, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(custommetricsResource, c.ns, name, data, subresources...), &v1alpha1.CustomMetric{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CustomMetric), err
}
