// Code generated by lister-gen. DO NOT EDIT.

package v1alpha2

// CustomMetricListerExpansion allows custom methods to be added to
// CustomMetricLister.
type CustomMetricListerExpansion interface{}

// CustomMetricNamespaceListerExpansion allows custom methods to be added to
// CustomMetricNamespaceLister.
type CustomMetricNamespaceListerExpansion interface{}

// ExternalMetricListerExpansion allows custom methods to be added to
// ExternalMetricLister.
type ExternalMetricListerExpansion interface{}

// ExternalMetricNamespaceListerExpansion allows custom methods to be added to
// ExternalMetricNamespaceLister.
type ExternalMetricNamespaceListerExpansion interface{}
